# Generated by Django 3.2.19 on 2023-07-05 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0056_enrollment_time_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLimits',
            fields=[
                ('course_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='grade_limits', serialize=False, to='course.courseinstance', verbose_name='LABEL_COURSE_INSTANCE')),
                ('limits', models.JSONField(blank=True, default=dict, verbose_name='LABEL_GRADE_LIMITS')),
            ],
        ),
    ]
